### ISSUE TITLE
Some ſuggeſtions.

### ISSUE THREAD

**Issue by Alice196498** [ctrlcctrlv/kjv1611#14] opened 2019-01-04 08:00 UTC
Seeing as this is one of the only complete founts of Blackletter in the Engliſh ſtyle, although to my knowledge many of theſe ſuggeſtions may not be preſent in the original printing of the Bible, I feel it may be beneficial to include them for the ſake of completeneſs and to the end of aſſiſting anyone intereſted in reproducing period works in this ſtyle.
 I have read the iſſue regarding the “ ye ” ligature (#2), and while I know not how it was implemented, I do have a ſuggeſtion to impove its functionality, and allow it to be uſed eaſily without ſpecial typeſetting ſoftware ; my ſolution is, thus :—Create a ſet of ſuperſcript letters that are kerned over the preceeding letter, or uſe the combining letters in Unicode (ſuch as U+0364). Doing it this way would not only allow the “ ye ” to be eaſily typeſet, but would alſo allow other abbreviations, ſuch as “ wch,” “ wt,” “ yr ” (which, with, your). Some other common abbreviations I’ve ſeen in ſome works are ỹ as in “ metỹg ” (metyng ; i. e., meeting), and ꝭ (U+A76D LATIN SMALL LETTER IS) as can be ſeen in the words “ ſpouſellꝭ ” and “ kingꝭ ” on [this page.](https://www.bl.uk/treasures/festivalbooks/pagemax.aspx?strFest=0073&strPage=1) I have alſo ſeen p̱ for “ per,” as ſeen in “ goodly p̱ſones ” on the antepenultimate line [here.](https://www.bl.uk/treasures/festivalbooks/pagemax.aspx?strFest=0008&strPage=4)
 Another ſuggeſtion I have is to include an alternate form of w, which is very popular in many Engliſh faces, that more cloſely reſembles v ; it can be ſeen on [this page.](https://www.bl.uk/treasures/festivalbooks/pagemax.aspx?strFest=0231&strPage=3)
 Finally, a few common ligatures ſeem to be miſſing ; namely, ct, ffi, ffl, ſb, ſk, ſl, ſſl. The leſs common in Engliſh, but ſtill uſeful to include are : ch, ck, fj, fij, ft, ſj, ſö, tt, and tz.

**Comment by ctrlcctrlv** [comment] 2019-01-04 08:51
I only added ligatures found in the 1611 KJV. The use of ꝭ you found in another book is quite interesting, if not a tad bizarre looking to modern eyes.

The "ye" ligature was implemented using the `hlig` OpenType feature. Special software not required, it can be easily typeset with either CSS or XeLaTeX + `fontspec`.

**Comment by artistofmind** [comment] 2019-01-14 22:47
(I was about to post a new issue when I remembered our friend Alice had already noticed this. So I include the following as experiential corroboration — as it were a “+1” — with an example, and one additional proposal, FYI.)

[F]or feare of the oppꝛeſſing ſwoꝛd, they ſhall turne euery one to his people[.]
— Ieremiah [l : 16](https://www.kingjamesbibleonline.org/1611_Jeremiah-Chapter-50/#16) (p. 872)

While studying today, I noticed this seemed apropos of the “oppressor / oppressed” narrative in today’s identity politics. (I guess there is nothing new under the sun.) ;) In attempting to recreate the verse in question with your font, so as to quote it in my own work, I also noticed that, while your ſſ & ſi ligatures are present, ſſi is missing. (It just uses the ſſ ligature, then has a wide gap before the “i.”) I checked, and the same is true for ſſl, ffi & ffl. (Though it’s less noticeable with the “f,” as the crossbar connects to the next letter, however imperfectly compared with the fi / fl ligatures.) So a combinatory ligature should probably be added, at some point in the future.

Also, I am not sure yet if ſſt (e.g. misstatement) or fft (e.g. offtrack) are used in the Bible (if they are, they occur quite rarely), but I suppose you might consider adding them as well. (Boy, there are a lot of factors that go into making a typeface!)

**Comment by Alice196498** [comment] 2019-01-14 23:29
I know that no Roman typefaces traditionally include a ligature for ſſt or fft, and would generally ſet them as either ſst, sſt (depending on context), and ff [ligature] t, but I believe I may have ſeen ſome in one or two Blackletter typefaces. In a modern typeface or fount, there’s no good reaſon not to include theſe ligatures in the dlig table, at leaſt. The reaſon I ſay to include them in the dlig table and not as default ligatures is ſimply that, ſeeing as ſorts like ft, fft, ſſt, and ſome others are either not traditionally uſed, or are uſed in rare occaſions or for ſpecifick reaſons, it’s generally beſt to keep them out of the default ſet, and let the typeſetter decide whether to uſe them or not in a given Work or ſituation.

**Comment by artistofmind** [comment] 2019-01-15 00:25
Alice,

EB Garamond has fft & ſſt. :) (As far as their being “traditional,” I shall have to consult the [First Folio](http://firstfolio.bodleian.ox.ac.uk/text/01) of Shakespeare’s plays, and get back to you.)

**Comment by Alice196498** [comment] 2019-01-15 00:38
EB Garamond does have thoſe ligatures—I apologize for my misſtatement. I was referring more to the fuſil types uſed in the 18th century and many earlier Engliſh printing typefaces with my original ſtatement ; I ſhould have been more clear on that. A few good modern typefaces include thoſe ſorts. As for old metal types, they generally didn’t have ligatures for thoſe made becauſe of how uncommon they are, I think. That being ſaid, a ligature of ft iſn’t  ſomething I generally ſee in older works.

**Comment by ctrlcctrlv** [comment] 2019-01-15 01:07
Jeremiah 50:16 is split at the longs/longs_i boundary:

![cut](https://user-images.githubusercontent.com/838783/51151135-87967b00-18a4-11e9-9fc3-2a6c36920586.png)

I should be able to fix these with a kern, i.e.:

![longs-longs_i](https://user-images.githubusercontent.com/838783/51151215-f673d400-18a4-11e9-91d5-728632de26b4.png)

**Comment by Alice196498** [comment] 2019-01-15 02:39
In the caſe of ſſi, for this fount, a kern is a good ſolution, in my opinion. Speaking of kerning, the kerning after ſſ, around ꝛ, and amond ſeveral pairs of letters ſeems to be a little off—either too wide, or too narrow. I’ve typeſet the above paſſage and included a few words to illuſtrate ſome of the iſſues with kerning that I’m noticing.
 I ſhall uſe ſome words from the paſſage as an example, as well as the three words below it : The kerning in _Babylon_ is a little looſe, but it’s wide in _him ;_ the kerning between _a_ & _n_ in _and_ is too wide, making it look almoſt like “ a nd.” In _ſhall,_ _ſh_ and _a_ are nearly touching, _a_ and _l_ and quite far, and the two l’s are very looſe ; whereas in the paſſage, all the ſorts are ſpaced quite evenly apart, and ſomewhat cloſe. In _oppꝛeſſing,_ the ſpace between _p_ and _ꝛ_ is much too great, but between _ꝛ_ and _e,_ ſpace is wanting—the ſpace between the reſt of the letters is ſlightly looſe. In iſſue, _ſſ_ and _u_ are too far from each other, and _u_ & _e_ are perhaps too cloſe, or at leaſt, not in-tune with the reſt of the letters. In _connect,_ _n_ & _n_ are too far apart, and _e_ & _c_ are too cloſe.

![jeremiah 5016](https://user-images.githubusercontent.com/30258857/51154646-f3ceaa00-18b7-11e9-9602-29a7afcff6aa.png)

**Comment by ctrlcctrlv** [comment] 2019-01-15 03:26
@Alice196498 This font was for the most part automatically kerned. I'll fix the "n n" sequence kern, the only kern in your example I feel is seriously off; feel free to contribute better kerns for the minor other problems.

**Comment by artistofmind** [comment] 2019-01-15 05:26
In a word: yes. ^_^

I neglected to mention that the verse in my example, _with the original column width,_ is technically inapplicable. I could of course have found a second verse where the line was split differently, and cited that also. But as I said, I was not actually recreating the original passage in its entirety, but rather quoting from it using your font, which is how I noticed the missing ligature. So this is more of a general case; but as that passage led to my (independent) discovery of this oversight, I felt it worth mentioning. (Really I could have left out everything, save the bit about "__t" ligatures, which were the only ones Alice hadn't already mentioned. And which, as we both observed, are possibly not in the Bible at all, yet might be nice to have anyway.)

Alice's observations concerning the kerning are very astute, and I concur therewith.

**Comment by artistofmind** [comment] 2019-01-15 05:42
OK, I found another (better) source: [Numbers xxiiij:18](https://www.kingjamesbibleonline.org/1611_Numbers-Chapter-24/#18) (p. 251). It occurs twice in the same verse. :)

**Comment by ctrlcctrlv** [comment] 2019-01-28 13:55
Closing for now. Please refrain from making issues that contain more than one bug/suggestion in the future, make a new issue for each request. Thanks :smile:

**Closed as completed by ctrlcctrlv** 2019-01-28 13:55 UTC
Labels: enhancement

**Comment by artistofmind** [comment] 2019-02-15 08:01
I didn’t create this issue, and am new to the GitHub world (and you are, again, welcome to edit the issues I do post, in whatever way you see fit), but I take your meaning and will try to honor that request in future.

BTW, I still have not finished cropping those letters to my satisfaction, but am aiming for this weekend. (Fingers crossed.) And I just wanted to say, I really, _really_ appreciate your work. If I sound overly critical, it’s not my intention to insult you — it never entered my mind (until now, thinking to say this). I appreciate that this is your hobby, and it is a challenging project by its very nature (reverse engineering a typeface from pixelly, blurry, sometimes two-color-only scans of documents that were physically flawed to begin with). You do exceptionally fine work, and I am only trying to help, by bringing things I notice to your attention (always citing my source, of course). My motivation is partly selfish — because my own project involves reproducing every jot & tittle & space in the Originall [sic] document in a searchable, linkable, copy-&-pastable, infinitely scalable form — but not completely selfish, as I genuinely believe you, and every other user of this typeface, will benefit from the improved accuracy of your updated letterforms. :)

And your diligence inspires me. I did not expect you would release a new version so soon! And it is very definitely an improvement over the last one.

Peace be unto you, brother. Know that you are loved, and your work is appreciated.

**Comment by ctrlcctrlv** [comment] 2019-02-15 09:34
Thank you :+1: :smiley:

**Comment by ctrlcctrlv** [comment] 2019-02-19 10:47
> Another ſuggeſtion I have is to include an alternate form of w, which is very popular in many Engliſh faces, that more cloſely reſembles v

I think this is done in the latest revision as `w.alt2`, in stylistic set 2 (`ss02`).

**Comment by Alice196498** [comment] 2019-02-19 20:32
Indeed, it is done. Thank you. This ſhall allow for more accurate repreſentation of many texts, as well as give the typeſetter more choice in how they wiſh to diſplay the work.
